exercise/urls.py
from django.urls import path
from . import views

app_name = 'exercise'

# URL pattern to be used by the application
urlpatterns = [
    # path: /exercise/...
    path('landing/', views.route_to_landing_or_home, name="landing"),
    path('register/', views.register_user, name="register"),
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('firstlogin/', views.first_login, name='firstlogin'),
    path('home/', views.home, name='home'),
    path('blog/', views.blog_display, name='blog'),
    path('blog/submit/', views.blog_post, name='submit'),
    path('sports/getsportsxp/', views.read_sportsxp, name='getsportsxp'),
    path('sports/updatesportsxp/', views.update_sportsxp, name='updatesportsxp'),
    path('sports/sortxp/', views.sortxp, name='sortxp'),
    path('search/youtube/', views.search_youtube, name="youtube"),
    path('instructions/', views.sport_redirect, name="sportinstruction"),
    path('instructions/cardio/', views.cardioView, name="cardio"),
    path('instructions/bodybuilding/', views.bodyView, name="body"),
    path('instructions/sports/', views.sportView, name="sport"),
    path('exercise_logging/', views.exercise_logging, name='exerciselogging'),
    path('bmi/', views.bmi_display, name="bmidisplay"),  # page for bmi display
    path('friends/', views.friendship, name="friendship"),
    path('friend/friendrequest/',
         views.send_friend_request, name='friendrequest'),
    path('friend/decision/<str:action_user_name>/',
         views.accept_deny_block_request, name='decidefriend'),
    path('instructions/complete/', views.complete_instructions, name='complete')
]

exercise_gamification/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from exercise import views
# Following patterns for application are used in the app. See README: 3,4,5
urlpatterns = [
    path('', TemplateView.as_view(template_name="exercise/index.html")),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('exercise/', include('exercise.urls', namespace="exercise")),
    path('friendship/', include('friendship.urls')),
]

exercise/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Profile(models.Model):
    '''
    Profile model

    Note: This is user specific and needs a user to be accessed.  
    '''
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)  # Ties the info to the user
    # Info to see if this is the users first time logging in
    first_login = models.BooleanField(default=True)
    bio = models.TextField(default="")

    def __str__(self):
        return self.user.username


class SportsXP(models.Model):
    '''
    Sports model to use for the sports XP bar
    '''
    user = models.OneToOneField(
        User, on_delete=models.CASCADE)     # Ties the info to the user
    timestamp = models.DateTimeField(default=timezone.now)
    basketball = models.PositiveIntegerField(default=0)
    cross_training = models.PositiveIntegerField(default=0)
    cardio = models.PositiveIntegerField(default=0)
    strength_training = models.PositiveIntegerField(default=0)
    climbing = models.PositiveIntegerField(default=0)
    soccer = models.PositiveIntegerField(default=0)
    american_football = models.PositiveIntegerField(default=0)
    dance = models.PositiveIntegerField(default=0)
    gymnastics = models.PositiveIntegerField(default=0)
    hiking = models.PositiveIntegerField(default=0)
    swimming = models.PositiveIntegerField(default=0)
    yoga = models.PositiveIntegerField(default=0)
    total_xp = models.PositiveIntegerField(default=10)

    def __str__(self):
        return '%s %s %s %s %s %s %s %s %s %s %s %s %s' % (self.basketball, self.cross_training, self.cardio,
                                                           self.strength_training, self.climbing, self.soccer,
                                                           self.american_football, self.dance, self.gymnastics,
                                                           self.hiking, self.swimming, self.yoga, self.timestamp)


class Blog(models.Model):
    '''
    Blog model

    Note: Not user specific. This is just for the blog page. 
    '''
    blog_post = models.CharField(default="", max_length=500)
    blog_user = models.CharField(default="", max_length=200)
    date_published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.blog_user


class Exercise(models.Model):
    '''
    Exercise model
    User specific. Logs their exercises
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exercise_name = models.CharField(max_length=200, default="")
    reps = models.PositiveIntegerField(default=0)
    sets = models.PositiveIntegerField(default=0)
    weight_in_pounds = models.PositiveIntegerField(default=0)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.exercise_name


class Bmi(models.Model):
    '''
    bmi model
    User specific. keeps track of their curretn bmi,
    as well as their progress towards their goal.
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bmi_user = models.CharField(default="", max_length=200)
    height_feet = models.PositiveIntegerField(default=0)
    height_inches = models.PositiveIntegerField(default=0)
    weight_pounds = models.PositiveIntegerField(default=0)
    time_of_bmi = models.DateTimeField(default=timezone.now)  # do i want this?
    user_bmi = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.bmi_user


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


# @receiver(post_save, sender=User)
# def create_sports_xp(sender, instance, created, **kwargs):
#     if created:
#         SportsXP.objects.create(user=instance)
#     instance.sportsxp.save()


# @receiver(post_save, sender=User)
# def save_sports_xp(sender, instance, **kwargs):
#     instance.sportsxp.save()

exercise/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from exercise.models import Exercise, Bmi


class CreateUserForm(UserCreationForm):
    '''
    Form to be used when registering a new user manually without the use
    of google authentication.

    Uses the built in user model from Django (We don't need to create a new user Profile)
    '''

    class Meta:
        model = User
        # Information to be collected when registering a new user.
        fields = ['username', 'email', 'password1', 'password2']


class ExerciseForm(ModelForm):
    '''
    Form for storing user exercises
    '''
    class Meta:
        model = Exercise
        fields = ('exercise_name', 'reps', 'sets', 'weight_in_pounds')


# You can create other forms here to use (for example the one to be used on first login, but you have to still create a new page to then use the form in)


class BmiForm(ModelForm):
    '''
    Form for storing user height/weight, to calculate the user's bmi
    '''
    class Meta:
        model = Bmi
        fields = ('height_feet', 'height_inches', 'weight_pounds')
        # not included: user_bmi, timestamp

exercise/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import CreateUserForm
from .models import Profile, Blog, SportsXP
from .forms import CreateUserForm, ExerciseForm, BmiForm
from .models import Profile, Blog, Exercise, Bmi
from friendship.models import Friend, FriendshipRequest, Block
from isodate import parse_duration
from django.conf import settings
import datetime
import requests

#-----stuff to make dynamic progress bar work----------------#
sports_list = {
    'Basketball': ['basketball', 0],
    'Cross Training': ['cross_training', 0],
    'Cardio': ['cardio', 0],
    'Strength Training': ['strength_training', 0],
    'Climbing': ['climbing', 0],
    'Soccer': ['soccer', 0],
    'American Football': ['american_football', 0],
    'Dance': ['dance', 0],
    'Gymnastics': ['gymnastics', 0],
    'Hiking': ['hiking', 0],
    'Swimming': ['swimming', 0],
    'Yoga': ['yoga', 0]
}

total_xp = 0

# ----- Views used for when the user has been logged in ------#


@login_required(login_url='exercise:login')
def home(request):
    '''
    Method to render the homepage (dashboard) of the user
    '''
    if request.user.profile.first_login:
        return HttpResponseRedirect(reverse('exercise:firstlogin'))

    update_xp(request)
    all_friends = Friend.objects.friends(request.user)
    unread_friend_requests_amount = Friend.objects.unrejected_request_count(
        user=request.user)
    my_user_id = User.objects.get(
        username=request.user.get_username()).pk
    try:
        friend_requests = Friend.objects.unrejected_requests(
            user=request.user)
    except:
        friend_requests = None

    context = {'sports': sports_list, 'all_friends': all_friends,
               'number_unread_requests': unread_friend_requests_amount, 'friend_requests': friend_requests,
               'total': total_xp}
    return render(request, 'exercise/home.html', context)


@login_required(login_url='exercise:login')
def first_login(request):
    '''
    Method to save the data from first time users
    '''
    print(request.POST)
    if request.method == 'POST':
        user = User.objects.get(pk=User.objects.get(
            username=request.user.get_username()).pk)  # Grabs user based on the id
        user.first_name = request.POST.get(
            'firstname')     # Adds to first name
        user.last_name = request.POST.get('lastname')   # Adds to last name
        user.profile.first_login = False  # Updates the first login
        user.profile.bio = request.POST.get('bio')  # Updates the bio field
        user.sportsxp = SportsXP()
        user.sportsxp.save()
        user.save()  # Saves the data
        return HttpResponseRedirect(reverse('exercise:home'))

    context = {}
    return render(request, 'exercise/firstlogin.html', context)


@login_required(login_url='exercise:login')
def exercise_logging(request):
    '''
    Method to save an exercise and view previous exercises
    '''
    global total_xp
    if request.user.profile.first_login:
        return HttpResponseRedirect(reverse('exercise:firstlogin'))

    if request.method == 'POST':
        user = User.objects.get(pk=User.objects.get(
            username=request.user.get_username()).pk)
        form = ExerciseForm(request.POST)

        if form.is_valid():
            form.instance.user = user
            update_xp(request)
            user.sportsxp.total_xp += 1
            user.sportsxp.save()
            form.save()
            # redirect to itself
            return HttpResponseRedirect(reverse('exercise:exerciselogging'))
    else:
        form = ExerciseForm()
        # Gets all the logged exercises of a user
        exercise = Exercise.objects.filter(user=request.user)
        # Gets all the friends of a user
        all_friends = Friend.objects.friends(request.user)
        # Gets all the exercises of user's friends
        friend_exercises = Exercise.objects.filter(user__in=all_friends)

        context = {'form': form, 'exercises': exercise,
                   'friend_exercises': friend_exercises}
        return render(request, 'exercise/exercise_logging_form.html', context)


@login_required(login_url='exercise:login')
def blog_post(request):
    '''
    Method to save items from a blog post
    '''
    global total_xp

    if request.user.profile.first_login:
        return HttpResponseRedirect(reverse('exercise:firstlogin'))
    try:
        now = datetime.datetime.now()
        blog = Blog(blog_post=request.POST['blog'],
                    blog_user=request.user.get_username(),
                    date_published=now)  # Makes an instance of the blog


    except (KeyError):  # Error handling
        context = {'blog': Blog, 'error': "An error has occurred"}
        return render(request, 'exercise/blog.html', context)
    else:
        update_xp(request)
        user = User.objects.get(pk=User.objects.get(username=request.user.get_username()).pk)
        user.sportsxp.total_xp = user.sportsxp.total_xp + 0.1
        user.sportsxp.save()
        blog.save()  # Saves the blog to the database

    return HttpResponseRedirect(reverse('exercise:blog'))


@login_required(login_url='exercise:login')
def read_sportsxp(request):
    if request.user.profile.first_login:
        return HttpResponseRedirect(reverse('exercise:firstlogin'))

    xp_update = update_xp(request)

    context = {'sportxplist': xp_update,
               'sports': sports_list, 'total': total_xp}
    return HttpResponseRedirect(reverse('exercise:home'))


@login_required(login_url='exercise:login')
def sport_redirect(request):
    if request.user.profile.first_login:
        return HttpResponseRedirect(reverse('exercise:firstlogin'))
    context = {}
    return render(request, 'exercise/instruction.html', context)


@login_required(login_url='exercise:login')
def friendship(request):
    if request.user.profile.first_login:
        return HttpResponseRedirect(reverse('exercise:firstlogin'))

    all_friends = Friend.objects.friends(request.user)
    unread_friend_requests_amount = Friend.objects.unrejected_request_count(
        user=request.user)
    my_user_id = User.objects.get(
        username=request.user.get_username()).pk
    try:
        friend_requests = Friend.objects.unrejected_requests(
            user=request.user)
    except:
        friend_requests = None

    context = {'sports': sports_list, 'all_friends': all_friends,
               'number_unread_requests': unread_friend_requests_amount, 'friend_requests': friend_requests,
               'total': total_xp}
    return render(request, 'exercise/friendship.html', context)


@login_required(login_url='exercise:login')
def update_sportsxp(request):
    global sports_list

    update_xp(request)

    if request.method == 'POST':
        if (request.POST.get('submit') == 'Submit'):
            for key, value in sports_list.items():
                if request.POST.get('activities') == key:
                    user = User.objects.get(pk=User.objects.get(
                        username=request.user.get_username()).pk)  # Grabs user based on the id

                    item_id = value[0]
                    value = getattr(user.sportsxp, value[0])

                    user.sportsxp.total_xp = user.sportsxp.total_xp + 1
                    user.sportsxp.basketball = value + 1
                    user.sportsxp.cross_training = value + 1
                    user.sportsxp.cardio = value + 1
                    user.sportsxp.strength_training = value + 1
                    user.sportsxp.climbing = value + 1
                    user.sportsxp.soccer = value + 1
                    user.sportsxp.american_football = value + 1
                    user.sportsxp.dance = value + 1
                    user.sportsxp.gymnastics = value + 1
                    user.sportsxp.hiking = value + 1
                    user.sportsxp.swimming = value + 1
                    user.sportsxp.yoga = value + 1
                    user.sportsxp.save(
                        update_fields=[item_id, 'total_xp'])
        elif (request.POST.get('reset') == 'Reset'):
            for key, value in sports_list.items():
                if request.POST.get('activities') == key:
                    user = User.objects.get(pk=User.objects.get(
                        username=request.user.get_username()).pk)  # Grabs user based on the id
                    item_id = value[0]
                    value = getattr(user.sportsxp, value[0])

                    user.sportsxp.total_xp = user.sportsxp.total_xp - value
                    user.sportsxp.basketball = 0
                    user.sportsxp.cross_training = 0
                    user.sportsxp.cardio = 0
                    user.sportsxp.strength_training = 0
                    user.sportsxp.climbing = 0
                    user.sportsxp.soccer = 0
                    user.sportsxp.american_football = 0
                    user.sportsxp.dance = 0
                    user.sportsxp.gymnastics = 0
                    user.sportsxp.hiking = 0
                    user.sportsxp.swimming = 0
                    user.sportsxp.yoga = 0
                    user.sportsxp.save(
                        update_fields=[item_id, 'total_xp'])
        elif (request.POST.get('resetall') == "Reset All"):
            user = User.objects.get(pk=User.objects.get(
                username=request.user.get_username()).pk)  # Grabs user based on the id
            for key, value in sports_list.items():
                user.sportsxp.total_xp = user.sportsxp.total_xp - \
                    getattr(user.sportsxp, value[0])

exercise/templates/exercise/fake.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is not real home</title>
</head>
<h3> Fake Home Page</h3>
<body>
<div>
    <a href="/exercise/schedule"> Cardio? </a>
</div>
<div>

    <a href="/exercise/schedule2"> Lifting? </a>
</div>
<div>
    <a href="/exercise/schedule3"> Sports? </a>
</div>

</body>
</html>

exercise/templates/exercise/footer.html
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <p class="navbar-brand">A-05 Team</p>
    <br />
    <p class="navbar-brand">&copy; Copyright 2021</p>
  </div>
</nav>

exercise/templates/exercise/friendship.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    {% load static %} {% load friendshiptags %} {% load socialaccount %}

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Quicksand"
    />
    <title>Friends</title>
    <style>
      #container {
        width: 100vw;
        height: 96vh;
        text-align: center;
        overflow: hidden;
      }
    </style>
  </head>
  <body>
    <header>{% include "./header.html" %}</header>
    <font face="Quicksand">
      <center>
        <div class="container">
          <form method="POST" action="{% url 'exercise:friendrequest' %}">
            {% csrf_token %}
            <div class="card text-center">
              <div class="card-header">Send a friend request!</div>
              <div class="card-body">
                <h5 class="card-title">
                  <input
                    type="text"
                    placeholder="Username of friend..."
                    name="friendusername"
                  />
                  <input
                    type="text"
                    placeholder="Message to friend..."
                    name="friendmessage"
                  />
                </h5>
                <input
                  type="submit"
                  value="Send Request"
                  name="sendfriendrequest"
                  class="btn btn-success"
                  style="display: block; margin: 0 auto"
                />
              </div>
              {% if error %}
              <div class="card-footer text-muted">{{ error }}</div>
              {% else %} {% endif %} {% if success_sent %}
              <div class="card-footer text-muted">{{ success_sent }}</div>
              {% else %} {% endif %}
            </div>
          </form>
          <br />
          <br />
          <div>
            {% if friend_requests %}
            <div>
              {% for possible_friend in friend_requests %}
              <div class="card text-center">
                <div class="card-header">
                  {{possible_friend.from_user}} would love to be your friend!
                </div>
                <div class="card-body">
                  <h5 class="card-title">
                    From: {{ possible_friend.from_user }}
                  </h5>
                  {% if possible_friend.message %}
                  <p class="card-text">"{{possible_friend.message}}"</p>
                  {% else %}
                  <p class="card-text">
                    "Message: "I would love to be your friend"
                  </p>
                  {% endif %}
                  <form
                    method="POST"
                    action="{% url 'exercise:decidefriend' possible_friend.from_user %}"
                  >
                    {% csrf_token %}
                    <a href="#" class="btn btn-success">
                      <input
                        type="submit"
                        value="Accept"
                        name="Decision"
                        class="btn btn-success"
                        style="display: block; margin: 0 auto"
                      />
                    </a>
                    <a href="#" class="btn btn-danger">
                      <input
                        type="submit"
                        value="Deny"
                        name="Decision"
                        class="btn btn-danger"
                        style="display: block; margin: 0 auto"
                      />
                    </a>
                    {% comment %}
                    <a href="#" class="btn btn-danger"
                      ><input
                        type="submit"
                        value="Block"
                        name="Decision"
                        class="btn btn-danger"
                        style="display: block; margin: 0 auto"
                      />
                    </a>
                    {% endcomment %}
                  </form>
                </div>
                <div class="card-footer text-muted">
                  Sent on: {{ possible_friend.created }}
                </div>
              </div>
              {% endfor%}
            </div>
            {% else %}
            <div>
              <div class="card text-center">
                <div class="card-header">
                  There are no current friend requests. Try sending some out!
                </div>
              </div>
            </div>
            {% endif %}
          </div>
          <br />
          <br />
          {% if all_friends %} {% for friend in all_friends%}
          <div class="card text-center">
            <div class="card-header">{{friend}} is one of your friends!</div>
            <div class="card-body">
              <form
                method="POST"
                action="{% url 'exercise:decidefriend' friend %}"
              >
                {% csrf_token %}
                <a href="#" class="btn btn-warning"
                  ><input
                    type="submit"
                    value="Unfriend"
                    name="Decision"
                    class="btn btn-warning"
                    style="display: block; margin: 0 auto"
                  />
                </a>
                {% comment %}
                <a href="#" class="btn btn-warning">
                  <input
                    type="submit"
                    value="Unblock"
                    name="Unblock"
                    class="btn btn-warning"
                    style="display: block; margin: 0 auto"
                  />
                </a>
                {% endcomment %}
              </form>
            </div>
          </div>
          {% endfor%} {% else %}
          <div>
            <div class="card text-center">
              <div class="card-header">
                You have no friends. Try making some!
              </div>
            </div>
          </div>
          {% endif %}
        </div>
      </center></font
    >
  </body>
</html>

exercise/templates/exercise/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %} {% load friendshiptags %} {% load socialaccount %}

    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Homepage</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
      integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Audiowide"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <style>
      body {
        font-family: "Audiowide", sans-serif;
      }
      .container-left {
        position: relative;
        width: 60vw;
      }
      .center {
        text-align: right;
        vertical-align: middle;
        color: black;
      }
      .left-bottom {
        text-align: left;
        vertical-align: bottom;
        color: black;
      }
      .vertical-center {
        display: flex;
        justify-content: center;
        align-items: center;
      }
      .title {
        color: black;
        font-size: 1.5vh;
      }
      .dropdown {
        position: relative;
        display: inline-block;
      }
    </style>
  </head>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="{% static 'exercise/images/logo.png' %}"
            alt=""
            width="50"
            height="40"
            class="d-inline-block align-text-center"
          />
        </a>
        <div class="container-left">
          <div class="left-bottom">
            {% if request.user.is_authenticated %}
            <h1 class="center">
              <div class="dropdown">
                <a href="{% url 'exercise:home' %}" class="navbar-brand"
                  ><p class="title">home</p></a
                >
              </div>
              <div class="dropdown">
                <a href="{% url 'exercise:blog' %}" class="navbar-brand"
                  ><p class="title">blog</p></a
                >
              </div>
              <div class="dropdown">
                <a
                  href="{% url 'exercise:exerciselogging' %}"
                  class="navbar-brand"
                  ><p class="title">exercise</p></a
                >
              </div>
              <div class="dropdown">
                <a href="{% url 'exercise:bmidisplay' %}" class="navbar-brand"
                  ><p class="title">bmi</p></a
                >
              </div>
              <div class="dropdown">
                <a
                  href="{% url 'exercise:sportinstruction' %}"
                  class="navbar-brand"
                  ><p class="title">sports</p></a
                >
              </div>
              {% if friend_requests %}
              <div class="dropdown">
                <a href="{% url 'exercise:friendship' %}" class="navbar-brand"
                  ><p class="title">friends-{{number_unread_requests}}</p></a
                >
              </div>
              {% else %}
              <div class="dropdown">
                <a href="{% url 'exercise:friendship' %}" class="navbar-brand"
                  ><p class="title">friends</p></a
                >
              </div>
              {% endif %}
              <div class="dropdown">
                <a href="{% url 'exercise:youtube' %}" class="navbar-brand"
                  ><p class="title">youtube</p></a
                >
              </div>
              <div class="dropdown">
                <a href="{% url 'exercise:logout' %}" class="navbar-brand"
                  ><p class="title">logout</p></a
                >
              </div>
            </h1>
            {% else %}
            <h1 class="center">
              <a href="{% url 'exercise:blog' %}" class="navbar-brand"
                ><p class="title">blog</p></a
              >
              <a href="{% url 'exercise:login' %}" class="navbar-brand"
                ><p class="title">login</p></a
              >
              <a href="{% url 'exercise:register' %}" class="navbar-brand"
                ><p class="title">sign up</p></a
              >
            </h1>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>
</html>

exercise/templates/exercise/schedule.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Cardio</title>

</head>
<body>
<h1>
    Wanna work on your cardio but don't like running?
</h1>
<h3>
    Do these:
</h3>
<div>
    Mountain Climbers (45 sec)
</div>
<div>
    30 seconds breaks
</div>
<div>
    Burpees (30 sec)
</div>
<div>
    30 seconds breaks
</div>
<div>
    Lunges (45 sec or 10 each leg)
</div>
<div>
    30 seconds breaks
</div>
<div>
    High Knees (45 sec)
</div>
<div>
    30 seconds breaks
</div>
<div>
    Squat Jumps (45 sec)
</div>
<div>
    30 seconds breaks
</div>
<div>
    Mountain Climbers (45 sec)
</div>
<div>
    30 seconds breaks
</div>
<div>
    Burpees (30 sec)
</div>


</body>
</html>

exercise/templates/exercise/schedule2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Body Builder</title>

</head>
<body>




<h1>
    Like lifting but need to get your form and endurance up?
</h1>
<h3>
    Do these:
</h3>
<h3>
    !PLEASE WORK WITH WEIGHTS YOU ARE COMFORTABLE WITH!
</h3>
<div>
    Bench press: 3 sets 10 reps each at 70% body weight (1 minute break in between sets)
</div>
<div>
    1 minute and 30 seconds breaks
</div>
<div>
    Rows (do pull ups if no rowing machine): 3 sets of 10 reps each at 60% body weight (1 minute break in between sets)
</div>
<div>
    1 minute and 30 seconds breaks
</div>
<div>
    Bicep curls: Using a 25 lb barbell do 7 reps going half way to the top, 7 reps starting from half and going full, 7 reps doing full reps (no breaks in between)
</div>
<div>
    1 minute and 30 seconds breaks
</div>
<div>
    Legs: 3 sets 10 reps each at 100% body weight (2 minute breaks in between sets)
</div>
<div>
    1 minute and 30 seconds breaks
</div>
<div>
    Tricep extension: 3 sets 10 reps each at 30 lb barbell (or whatever you are comfortable with)
</div>

</body>
</html>